### ISSUE TITLE
安装的时候报错了，希望能够支持aarch64，非常感谢大佬

### ISSUE THREAD

**Issue by bcvb2001** [williamfzc/findit#22]
[ 37%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/lzma/lzma_decoder.c.o
            [ 37%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/lzma/lzma_encoder.c.o
            [ 37%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/lzma/lzma_encoder_optimum_fast.c.o
            [ 37%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/lzma/lzma_encoder_optimum_normal.c.o
            [ 37%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/lzma/lzma_encoder_presets.c.o
            [ 37%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/rangecoder/price_table.c.o
            [ 37%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/arm.c.o
            [ 37%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/armthumb.c.o
            [ 37%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/ia64.c.o
            [ 38%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/powerpc.c.o
            [ 38%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/simple_coder.c.o
            [ 38%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/simple_decoder.c.o
            [ 38%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/simple_encoder.c.o
            [ 38%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/sparc.c.o
            [ 38%] Building C object Utilities/cmliblzma/CMakeFiles/cmliblzma.dir/liblzma/simple/x86.c.o
            [ 38%] Linking C static library libcmliblzma.a
            [ 38%] Built target cmliblzma
            [ 38%] Building C object Utilities/cmlibarchive/libarchive/CMakeFiles/cmlibarchive.dir/archive_acl.c.o
            In file included from /data/data/com.termux/files/usr/tmp/pip-install-fdcqy4g9/cmake_4c60df2d19bc499ba838b9fb07972e0e/CMake-src/Utilities/cmlibarchive/libarchive/archive_acl.c:40:
            In file included from /data/data/com.termux/files/usr/tmp/pip-install-fdcqy4g9/cmake_4c60df2d19bc499ba838b9fb07972e0e/CMake-src/Utilities/cmlibarchive/libarchive/archive_acl_private.h:35:
            In file included from /data/data/com.termux/files/usr/tmp/pip-install-fdcqy4g9/cmake_4c60df2d19bc499ba838b9fb07972e0e/CMake-src/Utilities/cmlibarchive/libarchive/archive_string.h:49:
            /data/data/com.termux/files/usr/tmp/pip-install-fdcqy4g9/cmake_4c60df2d19bc499ba838b9fb07972e0e/CMake-src/Utilities/cmlibarchive/libarchive/archive.h:101:10: fatal error: 'android_lf.h' file not found
            #include "android_lf.h"
                     ^~~~~~~~~~~~~~
            1 error generated.
            make[5]: *** [Utilities/cmlibarchive/libarchive/CMakeFiles/cmlibarchive.dir/build.make:76: Utilities/cmlibarchive/libarchive/CMakeFiles/cmlibarchive.dir/archive_acl.c.o] Error 1
            make[4]: *** [CMakeFiles/Makefile2:1990: Utilities/cmlibarchive/libarchive/CMakeFiles/cmlibarchive.dir/all] Error 2
            make[3]: *** [Makefile:166: all] Error 2
            make[2]: *** [CMakeFiles/CMakeProject-build.dir/build.make:88: CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-build] Error 2
            make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/CMakeProject-build.dir/all] Error 2
            make: *** [Makefile:136: all] Error 2
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-hqp93sty/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
                cmkr.make(make_args, install_target=cmake_install_target, env=env)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-hqp93sty/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 680, in make
                self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-hqp93sty/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 704, in make_impl
                raise SKBuildError(

            --------------------------------------------------------------------------------
            -- Trying "Ninja" generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying "Ninja" generator - failure
            --------------------------------------------------------------------------------

            --------------------------------------------------------------------------------
            -- Trying "Unix Makefiles" generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying "Unix Makefiles" generator - success
            --------------------------------------------------------------------------------

            Configuring Project
              Working directory:
                /data/data/com.termux/files/usr/tmp/pip-install-fdcqy4g9/cmake_4c60df2d19bc499ba838b9fb07972e0e/_skbuild/linux-aarch64-3.10/cmake-build
              Command:
                cmake /data/data/com.termux/files/usr/tmp/pip-install-fdcqy4g9/cmake_4c60df2d19bc499ba838b9fb07972e0e -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/data/data/com.termux/files/usr/tmp/pip-install-fdcqy4g9/cmake_4c60df2d19bc499ba838b9fb07972e0e/_skbuild/linux-aarch64-3.10/cmake-install/src/cmake/data -DPYTHON_VERSION_STRING:STRING=3.10.4 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/data/data/com.termux/files/usr/tmp/pip-build-env-hqp93sty/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/data/data/com.termux/files/usr/bin/python3 -DPython3_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.10 -DPython3_LIBRARY:PATH=/data/data/com.termux/files/usr/lib/libpython3.10.so -DPython_EXECUTABLE:FILEPATH=/data/data/com.termux/files/usr/bin/python3 -DPython_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.10 -DPython_LIBRARY:PATH=/data/data/com.termux/files/usr/lib/libpython3.10.so -DPYTHON_EXECUTABLE:FILEPATH=/data/data/com.termux/files/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/data/data/com.termux/files/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/data/data/com.termux/files/usr/lib/libpython3.10.so -DCMAKE_BUILD_TYPE:STRING=Release

            Traceback (most recent call last):

                =============================DEBUG ASSISTANCE=============================
                If you are seeing a compilation error please try the following steps to
                successfully install cmake:
                1) Upgrade to the latest pip and try again. This will fix errors for most
                   users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
                2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
                   order to retrieve the last manylinux1 compatible wheel.
                3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
                   requirements in order to retrieve the last manylinux1 compatible wheel.
                4) Open an issue with the debug information that follows at
                   https://github.com/scikit-build/cmake-python-distributions/issues

                Python: 3.10.4
                platform: Linux-4.4.22-user-g72fafe4-aarch64-with-libc
                machine: aarch64
                bits: 64
                pip: n/a
                setuptools: 65.5.0
                scikit-build: 0.15.0
                PEP517_BUILD_BACKEND=setuptools.build_meta
                =============================DEBUG ASSISTANCE=============================

            An error occurred while building with CMake.
              Command:
                cmake --build . --target install --config Release --
              Install target:
                install
              Source directory:
                /data/data/com.termux/files/usr/tmp/pip-install-fdcqy4g9/cmake_4c60df2d19bc499ba838b9fb07972e0e
              Working directory:
                /data/data/com.termux/files/usr/tmp/pip-install-fdcqy4g9/cmake_4c60df2d19bc499ba838b9fb07972e0e/_skbuild/linux-aarch64-3.10/cmake-build
            Please check the install target is valid and see CMake's output for more information.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
      Failed to build cmake
      ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
      WARNING: There was an error checking the latest version of pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.

**Comment by williamfzc** [comment]
问题在scikit自己的支持，我们也没法修改
尽量转向有专门团队支持的库的吧，例如 airtest
另目测是要在手机上跑python，这种坑极其多，不建议

**Comment by bcvb2001** [comment]
> 

牛的，我是从uiautomator2过来的，一看还有这么简单的调用识别也可以，才来问问的，加油大佬
